title: Lisa.dev
email: # wowthemesnet@gmail.com
timezone: 
future: true
url     : https://hsyeun.github.io/
baseurl: ''
permalink: # "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Lisa
disqus: 'devblog'
locale: ko_kr
lang: ko_kr
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
highlighter: rouge
sass:
  quiet_deps: true
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  lisa:
    name: Lisa
    display_name: # Sal
    avatar: # 'assets/images/sal.png'
    email: # wowthemesnet@gmail.com
    web: https://github.com/hsyeun
    twitter: # https://twitter.com/wowthemesnet
    description: "Web Developer"
    
# Social
social:
  instagram: # https://www.instagram.com/bootstrapstarter/
  facebook: # https://www.facebook.com/bootstrapstartercom-346329609045284
  twitter: # https://twitter.com/bstartercom

collections:
  posts:
    output: true

# Plugins
plugins: 
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
- jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 10
  collection: "posts"
  sort_field: "date"
  sort_reverse: true

autopages:
  enabled: true
  categories:
    enabled: true
    layouts:
      - categories.html
    title: ":cat"
    permalink: "/categories/:cat"
    pagination:
      enabled: true
      per_page: 10
      title: ":cat"
      permalink: "/categories/:cat/page:num"
      sort_field: "date"
      sort_reverse: true
  tags:
    enabled: false
  collections:
    enabled: false