name: Jekyll site CI

on:
  push:
    branches: ["branch"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Seoul
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2   # GitHub Pages 기본 호환 버전
          bundler-cache: true

      - name: Install dependencies
        run: |
          bundle config set path 'vendor/bundle'
          bundle install --without windows

      - name: Build site with Jekyll
        run: bundle exec jekyll build --trace

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4